[package]
name = "stagiaire"
version = "0.2.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/nthery/stagiaire"
keywords = [ "string", "interning", "symbol" ]
description = """
Yet another string interner.
"""

[dependencies]
lazy_static = "1.4.0"
